language: r
sudo: false
cache: packages
dist: trusty

r_binary_packages:
  - mapproj
  - ggplot2
  - maps

after_success:
  - Rscript -e 'covr::codecov()'

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: YOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=

